TK2PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hp_login.urls')),
    path('todo/',include('todo.urls')),
    path('nilai/',include('nilai.urls')),
    path('schedule/',include('schedule.urls')),
    path('notes/',include('notes.urls')),

]

nilai/urls.py
from django.urls import path

from . import views

app_name = 'nilai'

urlpatterns = [
    path('input_nilai', views.index, name='index'),
    path('daftar_nilai',views.daftar_nilai, name="daftar_nilai"),
    path('hapus/<hapus_id>[0-9]', views.hapus, name="hapus")
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

nilai/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
# Create your models here.

class rata_nilai(models.Model):
    nama_nilai = models.CharField(max_length=100)
    isian_nilai = models.PositiveIntegerField(null=True)

nilai/forms.py
from .models import rata_nilai
from django import forms

class Input_Form(forms.ModelForm):
    class Meta:
        model = rata_nilai
        fields = ['nama_nilai',
        'isian_nilai',]

    isian_nilai = forms.IntegerField(label='', required=True, min_value=0, widget=forms.NumberInput(attrs={'class':'form-control','id':'isian_nilai'}))
    nama_nilai = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs={'class':'form-control','id':'nama_nilai', 'placeholder':'contoh : UTS, UAS, Latihan'}))

nilai/views.py
from django.shortcuts import render, redirect
from .forms import Input_Form
from django.http import HttpResponseRedirect, HttpResponse
from .models import rata_nilai

# Create your views here.
respons = {}
def index(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
        return redirect('/nilai/daftar_nilai')
    respons['input_form'] = form
    return render(request, 'nilai/input_nilai.html', respons)

def daftar_nilai(request):
    tipe_nilai = rata_nilai.objects.all()
    respons['tipe_nilai'] = tipe_nilai
    return render(request,'nilai/daftar_nilai.html', respons)

def hapus(request, hapus_id):
    rata_nilai.objects.filter(id=hapus_id).delete()
    return redirect('/nilai/daftar_nilai')

nilai/templates/nilai/daftar_nilai.html
{% extends 'hp_login/index.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Daftar nilai kamu</h1>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Kategori</th>
            <th scope="col">Nilai</th>
          </tr>
        </thead>
        <tbody>
        {% if tipe_nilai %} {% for tipe in tipe_nilai %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{ tipe.nama_nilai }}</td>
            <td>{{ tipe.isian_nilai }}</td>
            <td><a href="{% url 'nilai:hapus' tipe.id %}" id="hapus">
              <button type="button" class="btn btn-danger">Hapus</button>
          </a>
        </td>
          </tr>
        {% endfor %}
        {% endif %}
        </tbody>
      </table>
      <a href="/nilai/input_nilai" id="input_nilai">
        <button type="button" class="btn btn-success">Tambah</button>
    </a>
</div>

{% endblock %}

nilai/templates/nilai/input_nilai.html
{% extends 'hp_login/index.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Ayo list nilai kamu</h1>
    <form class="input_teks" action="" method="POST">
        {% csrf_token %}
        <label for="p_latihan">Kategori nilai :</label> {{input_form.nama_nilai}}
        <br>
        <label for="p_uts">Nilai :</label> {{input_form.isian_nilai}}
        <br>
        <input type="submit" name="Masukkan" class="btn btn-primary button-submit" value="Simpan">
        <h5>Jika kamu sudah memiliki list nilai sebelumnya, 
            <a href="/nilai/daftar_nilai" id="daftar_nilai">
                <button type="button" class="btn btn-link"> klik disini</button>
            </a>
        </h5>
    </form>
</div>
{% endblock %}