TK2PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hp_login.urls')),
    path('todo/',include('todo.urls')),
    path('nilai/',include('nilai.urls')),
    path('schedule/',include('schedule.urls')),
    path('notes/',include('notes.urls')),

]

hp_login/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='hp_login'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.loginPage, name="loginPage"),
    path('accounts/', include('django.contrib.auth.urls')),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.index, name='index'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    activity = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.activity

todo/forms.py
from django import forms
from .models import Todo
# from django.contrib.auth.models import User

class TodoForm(forms.ModelForm):
    activity = forms.CharField(label='')
    activity.widget.attrs.update({
        'class':'todo-form', 
        'required':True,
        })
    description = forms.CharField(label='')
    description.widget.attrs.update({
        'class':'todo-form',
        'required':True,
        })

    class Meta:
        model = Todo
        fields = ('activity','description')
      

todo/views.py
from django.shortcuts import render,redirect
from .models import Todo
from .forms import TodoForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.forms.models import model_to_dict

# Create your views here.
@login_required
def index(request):
    activity = Todo.objects.all()
    formtambah= TodoForm()
    return render(request,'todo/todo.html',{
        'activity' : activity,
        'formtambah':formtambah,
    })

@login_required
def tambahTodo(request):
    formtambah= TodoForm(request.POST)
    if formtambah.is_valid():
        new_task=formtambah.save()
        print("berhasil save")
        return JsonResponse({'activity': model_to_dict(new_task)},status=200)
    else:
        return redirect('todo:index')
        
    

@login_required
def delete_todo(request, pk):
    activity = Todo.objects.get(pk=pk)
    activity.delete()
    return redirect('todo:index')

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>To Do List</title>
    <link href='https://fonts.googleapis.com/css?family=ABeeZee' rel='stylesheet'>
    <link href="{% static 'todo/style.css' %}" rel="stylesheet"  type="text/css" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="menu-navbar">
            <a class="nav-link menu" href="{% url 'hp_login:index' %}"><span style="color: white;">Home </span><span class="sr-only">(current)</span></a>
            <a class="nav-link menu" href="{% url 'schedule:index' %}"><span style="color: white;">Jadwal</span><span class="sr-only">(current)</span></a>
            <a class="nav-link menu" href="#"><span style="color: white;">Nilai </span><span class="sr-only">(current)</span></a>
            <a class="nav-link menu" href="{% url 'todo:index' %}"><span style="color: white;">To-do list</span> <span class="sr-only">(current)</span></a>
            <a class="nav-link menu" href="#"><span style="color: white;">Notes </span><span class="sr-only">(current)</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated%}
                    <li class="nav-item">
                        <span class="navbar-brand mb-0 h1">halo, {{user.username}}!</span>
                    </li>
                {% endif %}
                <li class="nav-item">
                    
                        {% if user.is_authenticated%}
                        <li>
                            <a class="nav-link" href="{% url 'hp_login:logout'%}">
                                <button class="btn btn-warning back-btn" type="submit">Log out</button>
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a class="nav-link" href="{% url 'hp_login:login'%}">
                                <button class="btn btn-warning back-btn" type="submit">Log in</button>
                            </a>
                        </li>
                        {% endif %}
                        <form class="form-inline">
                        
                    </form>
                </li>
            </ul> 
        </div>
    </nav>
    {% block content %}
    {% endblock %}

</body>
<script type="text/javascript" src="{% static 'todo/script.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

todo/templates/todo/todo.html
{% extends 'todo/base.html' %}
{% load static %}

{% block content %}
<body>
    
    <div class="container">
       <div class="row">
           <div class="col-sm-3">

            <h1>To-Do List</h1>
           </div>
           <div class="col">
            <button id="showFormButton" type="button" class="btn btn-success tambah-btn"><i class='fa fa-plus' style='font-size:18px'></i></button>
           
        </div>
       </div>
        
        <div class="row">
           <form action='' method="post" id="createTaskForm">
                {% csrf_token %}
                {{ formtambah.as_p }}
                
                    <a href ="{% url 'todo:tambah' %}"><button id="createButton" type="button" class="btn btn-success tambah-btn">tambah</button></a>
                
            </form>    
        </div>
        <div class="row">
            {% if activity %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Kegiatan
                            </th>
                            <th>
                                Deskripsi
                            </th>
                            <th>
                                
                            </th>
                        </tr>
                    </thead>
                    <tbody id="taskList">
                        {% for activities in activity %}
                        <tr id="lineData">
                            <td>
                                {{activities.activity}}
                            </td>
                                <td>
                                {{activities.description}}
                            </td>
                            <td>
                                <a href="{% url 'todo:delete' activities.pk %}"><button class="btn btn-success hapus-btn" type="submit"><i class='fa fa-trash' style='font-size:18px'></i></button></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>  
            {% else %}
                <h3>Tambahkan Todo list mu!</h3>
            {% endif %}
        </div>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
</html>