TK2PPW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hp_login.urls')),
    path('todo/',include('todo.urls')),
    path('nilai/',include('nilai.urls')),
    path('schedule/',include('schedule.urls')),
    path('notes/',include('notes.urls')),

]

hp_login/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='hp_login'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/login/', views.loginPage, name="loginPage"),
    path('accounts/', include('django.contrib.auth.urls')),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.index, name='index'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.tambahTodo, name="tambah"),
    path('<int:pk>/delete', views.delete_todo, name='delete'),
    
]

hp_login/models.py
from django.db import models

# Create your models here.

hp_login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    username = forms.CharField(label="")
    email = forms.CharField(label="")
    password1 = forms.CharField(widget=forms.PasswordInput(),label="")
    password2 = forms.CharField(widget=forms.PasswordInput(),label="")
    username.widget.attrs.update({'placeholder':'username', 'class':'input-box'})
    email.widget.attrs.update({'placeholder':'email', 'class':'input-box'})
    password1.widget.attrs.update({'placeholder':'enter password', 'class':'input-box'})
    password2.widget.attrs.update({'placeholder':'re-enter password', 'class':'input-box'})
    class Meta:
        model = User
        fields = ['username' , 'email', 'password1', 'password2']

hp_login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .forms import CreateUserForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib import messages


# Create your views here.
def index(request):
    return render(request,"hp_login/index.html")

def signup(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request,'registration success')

            return redirect('hp_login:login')
    else:
        form = CreateUserForm()
    return render(request,"hp_login/registration.html",{
        'form':form
    })

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('hp_login:index')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('hp_login:index')
			else:
				messages.info(request, 'username or password is incorrect')

		context = {}
		return render(request, 'registration/login.html', context)

hp_login/templates/hp_login/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>StudFriend.</title>
        <link rel="stylesheet" href="{% static 'hp_login/style.css' %}" type="text/css" media="screen">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
        crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="menu-navbar">
                <a class="nav-link menu" href="{% url 'hp_login:index' %}"><span style="color: white;">Home </span><span class="sr-only">(current)</span></a>
                {% if user.is_authenticated%}
                    <a class="nav-link menu" href="{% url 'schedule:index' %}"><span style="color: white;">Jadwal</span><span class="sr-only">(current)</span></a>
                    <a class="nav-link menu" href="#"><span style="color: white;">Nilai </span><span class="sr-only">(current)</span></a>
                    <a class="nav-link menu" href="{% url 'todo:index' %}"><span style="color: white;">To-do list</span> <span class="sr-only">(current)</span></a>
                    <a class="nav-link menu" href="#"><span style="color: white;">Notes </span><span class="sr-only">(current)</span></a>
                {% endif %}
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated%}
                        <li class="nav-item">
                            <span class="navbar-brand mb-0 h1">halo, {{user.username}}!</span>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        
                            {% if user.is_authenticated%}
                            <li>
                                <a class="nav-link" href="{% url 'hp_login:logout'%}">
                                    <button class="btn btn-warning back-btn" type="submit">Log out</button>
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a class="nav-link" href="{% url 'hp_login:login'%}">
                                    <button class="btn btn-warning back-btn" type="submit">Log in</button>
                                </a>
                            </li>
                            {% endif %}
                            <form class="form-inline">
                            
                        </form>
                    </li>
                </ul> 
            </div>
        </nav>
    
        <div class="container index">
          
        </div>
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

hp_login/templates/hp_login/registration.html
<!DOCTYPE html>
<html>
    
<head>
    <title>StudFriend.|Registration</title>
    <link rel="stylesheet" href="../../static/hp_login/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body class="register">
	<div class="container h-100">
        <div class="row">
            <div class="col-lg">
            </div>
            <div class="col-lg">
                <div class="register-box">
                    <div class="d-flex justify-content-center form-container">
                        <form method="POST" action="">
                            {% csrf_token %}
                            {{form.as_p}}
                            </div>
                            <a class="d-flex justify-content-center link-to-other" href="{% url 'hp_login:loginPage' %}">already have an account? log in</a>
                            <div class="d-flex justify-content-center mt-4">
                                <input class="btn btn-dark" type="submit" value="register">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
	</div>
</body>
</html>